# Generated by Django 5.0.2 on 2025-04-16 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_movie_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='movie',
        ),
        migrations.AddField(
            model_name='comment',
            name='movie_id',
            field=models.IntegerField(null=True),
        ),
    ]
